################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= GPUsift
# Cuda source files (compiled with cudacc)
CUFILES		:= sift-driver.cu
CUDEPS          := sift.cu sift.hpp
CDEPS           := sift-conv.tpp sift.ipp
# C/C++ source files (compiled with gcc / c++)
#CCFILES		:= vector_reduction_gold.cpp 
#CFILES		:= vector_reduction_gold.cpp 

################################################################################
# Rules and targets

include ../../common/common.mk
